// flow-typed signature: 6c6c26e359e2383fa6a0292d6cd77ca0
// flow-typed version: <<STUB>>/jest-glamor-react_v^4.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-glamor-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-glamor-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-glamor-react/dist/matchers' {
  declare module.exports: any;
}

declare module 'jest-glamor-react/dist/replace-selectors' {
  declare module.exports: any;
}

declare module 'jest-glamor-react/dist/serializer' {
  declare module.exports: any;
}

declare module 'jest-glamor-react/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-glamor-react/dist/matchers.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/matchers'>;
}
declare module 'jest-glamor-react/dist/replace-selectors.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/replace-selectors'>;
}
declare module 'jest-glamor-react/dist/serializer.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/serializer'>;
}
declare module 'jest-glamor-react/dist/utils.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/utils'>;
}
declare module 'jest-glamor-react/index' {
  declare module.exports: $Exports<'jest-glamor-react'>;
}
declare module 'jest-glamor-react/index.js' {
  declare module.exports: $Exports<'jest-glamor-react'>;
}
